
 TABLE products {
  product_code text 
  product_name text
  product_line text 
  product_scale text
  product_vendor text
  product_description text
  quantity_in_stock integer
  buy_price numeric
  msrp numeric
}


Table customers {
  customer_number integer
  customer_name text
  contact_last_name text
  contact_first_name text
  phone text
  address_line1 text
  address_line2 text
  city text
  state text
  postal_code text
  country text
  sales_rep_employee_number integer
  credit_limit numeric
}

Table employees {
  employee_number integer
  last_name text
  first_name text
  extension text
  email text
  office_code text
  reports_to integer
  job_title text
}


Table offices {
  office_code text
  city text
  phone text
  address_line1 text
  address_line2 text
  state text
  country text
  postal_code text
  territory text
}

Table orderdetails {

  order_number integer
  product_code text
  quantity_ordered integer
  price_each numeric
  order_line_number integer
}



Table orders {
  order_number integer
  order_date timestamp
  required_date timestamp
  shipped_date timestamp
  status text
  comments text
  customer_number integer
}


Table payments {
  customer_number integer
  check_number text
  payment_date date
  amount numeric
}

Table product_lines
{
  product_line text
  text_description text
  html_description text
  image text
}



Ref: "employees"."employee_number" < "customers"."sales_rep_employee_number"



Ref: "offices"."office_code" < "employees"."office_code"

Ref: "customers"."customer_number" < "payments"."customer_number"

Ref: "orders"."order_number" < "orderdetails"."order_number"

Ref: "customers"."customer_number" < "orders"."customer_number"

Ref: "product_lines"."product_line" < "products"."product_line"
